"use client";

import React, { useEffect, useRef } from 'react';
import { useChatStore } from '@/lib/stores/chatStore';
import { ChatMessage } from '@/components/chat/ChatMessage';
import { StreamingMessage } from '@/components/chat/StreamingMessage';
import { ChatInput } from '@/components/chat/ChatInput';
import { Button } from '@/components/ui/button';
import { Plus, MessageSquare, Archive, Star, Trash2, Loader2 } from 'lucide-react';
import { usePreview } from '@/hooks/usePreview';
import { PreviewFrame } from '@/components/preview/PreviewFrame';
import { PreviewControls } from '@/components/preview/PreviewControls';

export default function ChatsPage() {
  const {
    sessions,
    activeSessionId,
    messages,
    isLoading,
    isStreaming,
    streamingContent,
    streamingMessageId,
    loadSessions,
    createSession,
    setActiveSession,
    archiveSession,
    deleteSession,
    starSession,
    unstarSession,
  } = useChatStore();

  const preview = usePreview();
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Handle iframe refresh
  const handleRefreshPreview = () => {
    const iframe = document.querySelector('iframe');
    if (iframe && iframe.src) {
      iframe.src = iframe.src;
    }
  };

  // TEMP: Test preview functionality (remove after Phase 2 SSE integration)
  const handleTestPreview = async () => {
    try {
      // Create test HTML content
      const testHtml = `
        <html>
          <head>
            <style>
              body { font-family: system-ui; padding: 2rem; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; margin: 0; }
              h1 { font-size: 2.5rem; margin-bottom: 1rem; }
              p { font-size: 1.2rem; line-height: 1.6; }
              .card { background: rgba(255,255,255,0.1); padding: 2rem; border-radius: 1rem; backdrop-filter: blur(10px); margin-top: 2rem; }
              ul { list-style: none; padding: 0; }
              li { padding: 0.5rem 0; }
            </style>
          </head>
          <body>
            <h1>🎉 Preview Works!</h1>
            <p>This is a test preview generated by the NAVI preview service.</p>
            <div class="card">
              <h2>Phase 1 Complete ✅</h2>
              <ul>
                <li>✅ PreviewService (in-memory storage)</li>
                <li>✅ Auth-gated API endpoints</li>
                <li>✅ Restrictive CSP headers</li>
                <li>✅ Split-pane responsive layout</li>
                <li>✅ Iframe sandbox (allow-scripts only)</li>
              </ul>
              <p style="margin-top: 1rem; font-size: 0.9rem; opacity: 0.8;">
                Try the controls above to refresh, toggle visibility, or change device sizes!
              </p>
            </div>
          </body>
        </html>
      `;

      // Store in backend (for testing the API)
      const backendUrl = process.env.NEXT_PUBLIC_AEP_CORE || 'http://localhost:8787';
      await fetch(`${backendUrl}/api/preview/static`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: testHtml,
          content_type: 'html'
        })
      });

      // Use srcDoc to avoid cross-origin iframe restrictions
      preview.setPreviewHtml(testHtml);
    } catch (error) {
      console.error('Failed to create preview:', error);
      alert('Failed to create preview. Is the backend running on port 8787?');
    }
  };

  // Load sessions on mount
  useEffect(() => {
    loadSessions();
  }, [loadSessions]);

  // Auto-scroll to bottom when new messages arrive
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, streamingContent]);

  const handleNewChat = async () => {
    await createSession();
  };

  const activeChatSession = sessions.find((s) => s.id === activeSessionId);

  return (
    <div className="flex h-[calc(100vh-112px)] -mx-6 -my-6 lg:-mx-8 lg:-my-8 rounded-lg overflow-hidden shadow-2xl border border-border/50">
      {/* Sidebar - Chat History */}
      <div className="w-80 border-r border-border/70 flex flex-col bg-card/40 backdrop-blur-sm">
        <div className="p-4 border-b border-border">
          <Button onClick={handleNewChat} className="w-full">
            <Plus size={16} className="mr-2" />
            New Chat
          </Button>
        </div>

        <div className="flex-1 overflow-y-auto">
          <div className="p-2 space-y-1">
            {sessions.length === 0 ? (
              <div className="text-center text-muted-foreground py-8 px-4">
                <MessageSquare size={48} className="mx-auto mb-2 opacity-50" />
                <p className="text-sm">No chats yet</p>
                <p className="text-xs mt-1">Start a new conversation with NAVI</p>
              </div>
            ) : (
              sessions.map((session) => (
                <div
                  key={session.id}
                  className={`group relative p-3 rounded-lg cursor-pointer transition-colors ${
                    session.id === activeSessionId
                      ? 'bg-primary/10 border border-primary/20'
                      : 'hover:bg-muted'
                  }`}
                  onClick={() => setActiveSession(session.id)}
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">
                        {session.title || `Chat ${session.id.slice(0, 8)}`}
                      </p>
                      <p className="text-xs text-muted-foreground">
                        {new Date(session.updated_at).toLocaleDateString()}
                      </p>
                    </div>

                    <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      <Button
                        size="icon"
                        variant="ghost"
                        className="h-6 w-6"
                        onClick={(e) => {
                          e.stopPropagation();
                          session.starred
                            ? unstarSession(session.id)
                            : starSession(session.id);
                        }}
                      >
                        <Star
                          size={12}
                          className={session.starred ? 'fill-yellow-500 text-yellow-500' : ''}
                        />
                      </Button>

                      <Button
                        size="icon"
                        variant="ghost"
                        className="h-6 w-6"
                        onClick={(e) => {
                          e.stopPropagation();
                          archiveSession(session.id);
                        }}
                      >
                        <Archive size={12} />
                      </Button>

                      <Button
                        size="icon"
                        variant="ghost"
                        className="h-6 w-6 text-destructive"
                        onClick={(e) => {
                          e.stopPropagation();
                          if (confirm('Delete this chat?')) {
                            deleteSession(session.id);
                          }
                        }}
                      >
                        <Trash2 size={12} />
                      </Button>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Main Chat Area */}
      <div className={`${preview.visible ? "flex-1" : "flex-[2]"} flex flex-col`}>
        {activeSessionId ? (
          <>
            {/* Chat Header */}
            <div className="h-16 border-b border-border/70 flex items-center justify-between px-6 bg-card/60 backdrop-blur-md shadow-sm">
              <div>
                <h2 className="font-semibold">
                  {activeChatSession?.title || 'New Conversation'}
                </h2>
                <p className="text-xs text-muted-foreground">Chat with NAVI</p>
              </div>
              {/* TEMP: Test Preview Button (remove after Phase 2) */}
              <Button
                variant="outline"
                size="sm"
                onClick={handleTestPreview}
                className="text-xs"
              >
                🧪 Test Preview
              </Button>
            </div>

            {/* Messages */}
            <div className="flex-1 overflow-y-auto scroll-smooth bg-background/50">
              <div className="py-4">
                {isLoading ? (
                  <div className="flex items-center justify-center h-full">
                    <Loader2 className="animate-spin text-muted-foreground" />
                  </div>
                ) : messages.length === 0 ? (
                  <div className="flex flex-col items-center justify-center h-full text-center px-4">
                    <MessageSquare size={64} className="text-muted-foreground mb-4 opacity-50" />
                    <h3 className="text-lg font-semibold mb-2">Start a conversation</h3>
                    <p className="text-sm text-muted-foreground max-w-md">
                      Ask NAVI anything about your codebase, request changes, or get help with your project.
                    </p>
                  </div>
                ) : (
                  <>
                    {messages.map((message) => (
                      <ChatMessage
                        key={message.id}
                        role={message.role}
                        content={message.content}
                        timestamp={message.timestamp}
                      />
                    ))}

                    {isStreaming && streamingMessageId && (
                      <StreamingMessage content={streamingContent} />
                    )}

                    <div ref={messagesEndRef} />
                  </>
                )}
              </div>
            </div>

            {/* Input */}
            <ChatInput />
          </>
        ) : (
          <div className="flex-1 flex flex-col items-center justify-center text-center px-4">
            <MessageSquare size={80} className="text-muted-foreground mb-6 opacity-30" />
            <h2 className="text-2xl font-bold mb-2">Welcome to NAVI</h2>
            <p className="text-muted-foreground mb-6 max-w-md">
              Select a conversation from the sidebar or start a new chat to begin talking with your AI coding assistant.
            </p>
            <Button size="lg" onClick={handleNewChat}>
              <Plus size={18} className="mr-2" />
              Start New Chat
            </Button>
          </div>
        )}
      </div>

      {/* Preview Pane - Loveable-style live preview */}
      {preview.visible && (
        <div className="flex-1 border-l border-border/70 flex flex-col bg-card/40 backdrop-blur-sm">
          <PreviewControls
            previewUrl={preview.url || undefined}
            onRefresh={handleRefreshPreview}
            onToggleVisibility={preview.toggleVisibility}
            visible={preview.visible}
          />
          <div className="flex-1 overflow-hidden">
            <PreviewFrame
              src={preview.url || undefined}
              srcDoc={preview.html || undefined}
              className="h-full"
            />
          </div>
        </div>
      )}
    </div>
  );
}
