"""Auto generated by Alembic - do not edit."""

revision = "1c91f2192fb6"
down_revision = ("0031_metrics_learning", "0034_mcp_servers")
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
