
"""Auto generated by Alembic - do not edit."""

revision = '4463617a43cd'
down_revision = ('5e931bfc2aef', '6e9fd0fa3890')
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
