"""Auto generated by Alembic - do not edit."""

revision = "4bb1ad0958e2"
down_revision = ("d20e5d2ab917", "0024_connectors_ci_runs")
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
