"""Auto generated by Alembic - do not edit."""

revision = "4ebeed57d7a3"
down_revision = "58e1b14967eb"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
