"""Auto generated by Alembic - do not edit."""

revision = "58e1b14967eb"
down_revision = "d20e5d2ab917"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
