
"""Auto generated by Alembic - do not edit."""

revision = '5e931bfc2aef'
down_revision = ('0020_chat_history', '4ebeed57d7a3')
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
