
"""Auto generated by Alembic - do not edit."""

revision = '6e9fd0fa3890'
down_revision = '0023_change_sets'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
