
"""Auto generated by Alembic - do not edit."""

revision = 'ac41f03562df'
down_revision = ('0010_org_policy_test_coverage', '0020_extension_platform', '0021_extension_security', '4bb1ad0958e2')
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
