
"""Auto generated by Alembic - do not edit."""

revision = 'aced98884720'
down_revision = ('0026_org_ui_redirect_config', 'ac41f03562df')
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
