"""Auto generated by Alembic - do not edit."""

revision = "d20e5d2ab917"
down_revision = "0018_navi_memory"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    """No-op migration - tables already created in 0013_memory_graph.

    This migration was auto-generated but the tables (memory_node, memory_edge)
    already exist from migration 0013_memory_graph. Keeping this as a no-op
    to maintain the migration chain integrity for dependent migrations.
    """
    # pgvector extension is handled by 0012_pgvector_bm25 and 0027_navi_memory_system
    # Skip here to avoid transaction abort when extension is unavailable
    pass


def downgrade() -> None:
    """No-op downgrade - tables are managed by 0013_memory_graph."""
    pass
